---
application:
  name: "zhonger-github-io"
  project: "blog"
  organization: "QoveryCommunity"
routers:
- name: "main-zhonger-github-io"
  routes:
  - application_name: "zhonger-github-io"
    paths:
    - "/*"
