name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ruby-latest

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
      - run: |
             gem install jekyll bundler
             bundle install
             jekyll build
      - uses: actions/upload-artifact@v2.3.1
        with:
          path: _site
